okta:
  oauth2:
    client-id: ${APP_OKTA_OAUTH2_CLIENT_ID}
    client-secret: ${APP_OKTA_OAUTH2_CLIENT_SECRET}
    issuer: https://${APP_OKTA_OAUTH2_ISSUER}/
    groups-claim: https://spring-boot.example.com/roles
